import React from 'react';
import type {GuestRequestProgress,LanguageCode} from '../api';
import {localeFor,t,statusLabel} from '../i18n';
import {useModalFocus} from '../hooks/useModalFocus';
interface Props{isOpen:boolean;progress:GuestRequestProgress|null;error:string;language:LanguageCode;busy:boolean;onClose:()=>void;onCancelRequest:()=>void;onModifyRequest:()=>void;onSubmitFeedback:(rating:number,note:string)=>void;}
export const TicketModal:React.FC<Props>=({isOpen,progress,error,language,busy,onClose,onCancelRequest,onModifyRequest,onSubmitFeedback})=>{
 const titleId=React.useId();
 const [rating,setRating]=React.useState(5);const [note,setNote]=React.useState('');
 React.useEffect(()=>{if(progress?.id){setRating(5);setNote('');}},[progress?.id]);
 const dialogRef=useModalFocus(isOpen,onClose);
 if(!isOpen)return null;
 const pendingChange=progress?.change_state==='cancel_requested'||progress?.change_state==='modify_requested';
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
  <div ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className="bg-white max-w-lg w-full overflow-hidden shadow-2xl border border-brand-borderLight flex flex-col max-h-[90vh] rounded-lg outline-none">
   <div className="flex justify-between items-center px-6 py-4 border-b border-[#E8DFC9] bg-[#FAF7F2]"><h3 id={titleId} className="font-serif font-bold text-lg text-brand-navyDark">{t(language,'requestActivity')}</h3><button type="button" className="min-w-11 min-h-11 inline-flex items-center justify-center rounded-lg" onClick={onClose} aria-label={t(language,'close')}>✕</button></div>
   <div className="p-6 space-y-4 overflow-y-auto text-xs" aria-live="polite">{error&&<p role="alert" className="text-rose-700">{error}</p>}{!progress&&!error&&<p>{t(language,'loadingProgress')}</p>}{progress&&<><p className="font-mono break-all">{progress.id}</p><p>{t(language,'status')}: <strong>{statusLabel(language,progress.status)}</strong></p><p>{t(language,'submittedDisclaimer')}</p>{progress.change_state&&progress.change_state!=='none'&&<p className="rounded-lg border border-[#E9E1D2] bg-[#FAF7F2] p-3 text-[#73532C]">{progress.change_state==='cancel_requested'?t(language,'cancelPending'):progress.change_state==='modify_requested'?t(language,'modifyPending'):progress.change_state==='cancelled'?t(language,'cancelAccepted'):progress.change_state==='modified'?t(language,'modifyAccepted'):t(language,'changeRejected')}</p>}<div className="pl-5 border-l-2 border-[#D9CEBC] space-y-4">{progress.status_history.map((m,i)=><div key={i}><strong>{statusLabel(language,m.status)}</strong><p className="text-gray-500">{m.at?new Date(m.at*1000).toLocaleString(localeFor(language)):t(language,'notRecorded')}</p></div>)}</div>{progress.status==='completed'&&progress.feedback_requested&&!progress.feedback_submitted&&<form className="rounded-lg border border-[#E9E1D2] bg-[#FAF7F2] p-4 space-y-3" onSubmit={event=>{event.preventDefault();onSubmitFeedback(rating,note);}}><p className="font-semibold text-brand-navyDark">{t(language,'feedbackPrompt')}</p><label className="block">{t(language,'feedbackRating')}<select value={rating} onChange={event=>setRating(Number(event.target.value))} className="ml-2 rounded border p-1" aria-label={t(language,'feedbackRating')}>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="block">{t(language,'feedbackNote')}<textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={300} className="mt-1 w-full rounded border p-2" rows={2}/></label><button disabled={busy} className="min-h-10 rounded bg-[#142742] px-3 py-2 text-white disabled:opacity-50" type="submit">{t(language,'feedbackSubmit')}</button></form>}{progress.feedback_submitted&&<p className="rounded border border-emerald-200 bg-emerald-50 p-3 text-emerald-800">{t(language,'feedbackSubmitted')}</p>}</>}</div>
   <div className="px-6 py-3 bg-[#FAF7F2] border-t border-[#E8DFC9] flex flex-wrap justify-end gap-2">{progress?.can_modify&&<button disabled={busy} className="min-h-11 px-4 py-2 rounded-lg border border-[#142742] text-[#142742] disabled:opacity-50" onClick={onModifyRequest}>{t(language,'modifySubmitted')}</button>}{progress?.can_cancel&&<button disabled={busy} className="min-h-11 px-4 py-2 rounded-lg border border-[#B89B6A] text-[#73532C] disabled:opacity-50" onClick={onCancelRequest}>{t(language,'cancelSubmitted')}</button>}<button className="min-h-11 px-4 py-2 rounded-lg bg-[#142742] text-white text-xs" onClick={onClose}>{t(language,'close')}</button></div>
  </div>
 </div>;
};
